links/urls.py
from django.urls import path

from .views import LinkCreateView, LinkList, LinkModifyView, SearchResultsList

app_name = "links"

urlpatterns = [
    path("", LinkList.as_view(), name="all_links"),
    path("search/", SearchResultsList.as_view(), name="search_results"),
    path("create/", LinkCreateView.as_view(), name="link-create"),
    path("modify/<uuid:lid>", LinkModifyView.as_view(), name="link-modify"),
]

links/models.py
import uuid

from django.db import models


class Link(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.TextField(max_length=1024, db_index=True, null=False)
    url = models.URLField(max_length=1024, db_index=True, null=False)
    type_choices = [
        ("blog", "Blog"),
        ("blog-post", "Blog-post"),
        ("project", "Project"),
        ("docs", "Documentation"),
        ("feed", "Feed"),
        ("podcast", "Podcast"),
        ("site", "Site"),
        ("git", "Git-repo"),
        ("forum", "Forum"),
        ("forum-post", "Forum-post"),
        ("video", "Video"),
    ]
    type = models.CharField(
        max_length=10, choices=type_choices, db_index=True, null=False
    )
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "url",
            "type",
        )

    def formatted_data(self):
        return f"{self.id}: {self.url}"

links/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from .models import Link


class LinkFormCreate(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "id-create-new-link"
        self.helper.form_class = "blueForms"
        self.helper.form_method = "post"
        self.helper.form_action = ""

        self.helper.add_input(Submit("submit", "Save"))

    class Meta:
        model = Link
        fields = ["url", "description", "type"]


class LinkFormModify(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "id-modify-link"
        self.helper.form_class = "blueForms"
        self.helper.form_method = "post"
        self.helper.form_action = ""

        self.helper.add_input(Submit("submit", "Modify"))

    class Meta:
        model = Link
        fields = ["description", "type"]
        readonly_fields = ["id", "url", "created_at", "updated_at"]

links/views.py
import time

from django.contrib import messages
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db import DatabaseError, IntegrityError, OperationalError, transaction
from django.http import HttpResponseNotFound, HttpResponseServerError
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic.list import ListView

from .forms import LinkFormCreate, LinkFormModify
from .models import Link


class LinkCreateView(View):
    form_class = LinkFormCreate
    template_name = "link_form.html"
    success_url = "/links/"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_link = None
            succeed = False
            giving_up = False
            try:
                with transaction.atomic():
                    new_link = form.save()
            except (IntegrityError, DatabaseError, OperationalError):
                transaction.rollback()
                count = 0
                while not succeed or not giving_up:
                    try:
                        time.sleep(10)
                        with transaction.atomic():
                            new_link = form.save()
                    except (IntegrityError, DatabaseError, OperationalError):
                        transaction.rollback()
                        count = count + 1
                        if count > 6:
                            new_link = None
                            giving_up = True
            if new_link is None:
                messages.error(
                    request,
                    "Sorry, we couldn't process your request because of a server error. Please \
                try again later.",
                )
                return render(request, self.template_name, {"form": form})
            return redirect(f"/links/modify/{new_link.pk}")
        else:
            new_url = form.cleaned_data["url"]
            new_type = form.cleaned_data["type"]
            old_link = Link.objects.get(url=new_url, type=new_type)
            return redirect(f"/links/modify/{old_link.pk}")


class LinkModifyView(View):
    form_class = LinkFormModify
    success_url = "/links/"
    template_name = "link_modify.html"
    object_id = None

    def get(self, request, lid):
        try:
            link = Link.objects.get(id=lid)
        except Link.DoesNotExist:
            return HttpResponseNotFound("The object was not found.")
        except DatabaseError:
            return HttpResponseServerError(
                "An error occurred while retrieving the object."
            )
        form = self.form_class(instance=link)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            succeed = False
            giving_up = False
            oid = kwargs.get("lid")
            try:
                with transaction.atomic():
                    link_to_modify = Link.objects.get(pk=oid)
                    setattr(
                        link_to_modify,
                        "description",
                        form.cleaned_data.get("description"),
                    )
                    setattr(link_to_modify, "type", form.cleaned_data.get("type"))
                    link_to_modify.save()
            except (IntegrityError, DatabaseError, OperationalError):
                transaction.rollback()
                count = 0
                while not succeed or not giving_up:
                    try:
                        time.sleep(10)
                        with transaction.atomic():
                            link_to_modify = Link.objects.get(pk=oid)
                            setattr(
                                link_to_modify,
                                "description",
                                form.cleaned_data.get("description"),
                            )
                            setattr(
                                link_to_modify, "type", form.cleaned_data.get("type")
                            )
                            link_to_modify.save()
                    except (IntegrityError, DatabaseError, OperationalError):
                        transaction.rollback()
                        count = count + 1
                        if count > 6:
                            giving_up = True
            return redirect("/links/")


@method_decorator(cache_page(60 * 5), name="dispatch")
class LinkList(ListView):
    model = Link
    context_object_name = "links"
    template_name = "link_list.html"


class SearchResultsList(ListView):
    model = Link
    context_object_name = "links"
    template_name = "search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        search_vector = SearchVector("description")
        search_query = SearchQuery(query)
        return (
            Link.objects.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)
            )
            .filter(search=search_query)
            .order_by("-rank")
        )

links/templates/link_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>Add a new link</h2>
  <form method="post">
     <div class="mb-3">
        {% csrf_token %}
        {{ form|crispy }}
        {% if redirect_field_value %}
          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
        <input type="submit" value="Save">
     </div>
  </form>
{% endblock %}

links/templates/link_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <br><br>
    <h1>Links</h1>
    <br><br>
    <form action="{% url 'links:search_results' %}" method="get">
      <input type="search" name="q" placeholder="Search by description..." class="form-control">
    </form>
    <br><br>
    <p><a href="{% url 'links:link-create' %}">Add a new link</a></p>
    <br>
    <table class="table-dark table-bordered">
    <thead>
      <th scope="col">type</th>
      <th scope="col">URL</th>
      <th scope="col">description</th>
      <th scope="col">action</th>
    </thead>
    {% for link in links %}
      <tbody>
        <tr>
          <td><b>{{ link.type }}</b></td>
          <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
          <td>{{ link.description }}</td>
          <td><a href="{% url 'links:link-modify' lid=link.id %}">Modify</a></td>
        </tr>
    {% empty %}
      <p>The database is empty. Add some links.</p>
    {% endfor %}
    </table>
    <br><br>
  </div>
{% endblock %}

links/templates/link_modify.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>Modify link</h2>
  <p>{{ form.url.value }}</p>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Modify">
  </form>
{% endblock %}

links/templates/search.html
{% extends 'base.html' %}
{% block content %}
  <div>
    <br><br>
      <p><a href="{% url 'links:link-create' %}">Add a new link</a></p>
      <br>
      <table class="table-dark table-bordered">
      <thead>
        <th scope="col">type</th>
        <th scope="col">URL</th>
        <th scope="col">description</th>
        <th scope="col">action</th>
      </thead>
      {% for link in links %}
        <tbody>
          <tr>
            <td><b>{{ link.type }}</b></td>
            <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
            <td>{{ link.description }}</td>
            <td><a href="{% url 'links:link-modify' lid=link.id %}">Modify</a></td>
          </tr>
      {% empty %}
        <p>The database is empty. Add some links.</p>
      {% endfor %}
      </table>
      <br><br>
    </div>
{% endblock %}